---
output: html
html-table-processing: none
jupyter: python3
---

# Code Along in Python: Coffee Table

## Start

Setting up.

```{python}
import polars as pl
import polars.selectors as cs
from great_tables import GT, loc, style
```

Importing the data.

```{python}
coffee_sales = pl.DataFrame.deserialize("data/coffee-sales.json", format="json")

coffee_sales
```

Let's get the data into Great Tables.

```{python}
gt_tbl_1 = #

gt_tbl_1
```

## Structure Basics

Add a title to the table to explain contents.

```{python}
gt_tbl_2 = # (
    #gt_tbl_1
#)

gt_tbl_2
```

Group numerical columns with a spanner. One grouping should be for revenue columns, another should be for profit columns.

```{python}
gt_tbl_3 = # (
    #gt_tbl_2
#)

gt_tbl_3
```

Change Column labels for readability. The column names are:
`icon`, `product`, `revenue_dollars`, `revenue_pct`, `profit_dollars`, `profit_pct`, and `monthly_sales`.

```{python}
gt_tbl_4 = # (
    #gt_tbl_3
#)

gt_tbl_4
```

## Formatting Basics

Format the currency values to make them look better.

```{python}
gt_tbl_5 = # (
    #gt_tbl_4
#)

gt_tbl_5
```

Format the fractional values by turning them into percentages.

```{python}
gt_tbl_6 = # (
    #gt_tbl_5
#)

gt_tbl_6
```

## Styling with tab_style()

Add an 'aliceblue' background to columns pertaining to revenue.

```{python}
gt_tbl_7 = # (
    #gt_tbl_6
#)

gt_tbl_7
```

Add an 'papayawhip' background to columns pertaining to profit.

```{python}
gt_tbl_8 = # (
    #gt_tbl_7
#)

gt_tbl_8
```

Make the text bold in the bottom row (the totals column).

```{python}
gt_tbl_9 = # (
    #gt_tbl_8
#)

gt_tbl_9
```

## Three Last Things

Add a column of bar plots using the monthly revenue column.

```{python}
gt_tbl_10 = # (
    #gt_tbl_9
#)

gt_tbl_10
```

Add images to the `icon` column. The images are in the `img` directory.

```{python}
gt_tbl_11 = # (
    #gt_tbl_10
#)

gt_tbl_11
```

Turn the `None` cell into a blank cell.

```{python}
gt_tbl_12 = # (
    #gt_tbl_11
#)

gt_tbl_12
```
